title: PE/MC Conference Deadlines # (Maintained by @hi_shawnn)
# email: cledewang@xtu.edu.cn
description: Countdowns to PE/MC conference deadlines
author: Shawn

domain: "pemcdeadlines.ml"
baseurl: ""

twitter_inspirater_username: abhshkdz
twitter_username: hi_shawnn
twitter_hashtag: Power Electronics
github_username: milletbig
github_repo: pemc-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
